# Generated by Django 2.0.2 on 2019-11-23 02:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_proprietario_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietario',
            name='data_nascimento',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Nascimento'),
            preserve_default=False,
        ),
    ]
