# Generated by Django 2.0.2 on 2019-11-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_proprietario_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietario',
            name='cpf',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
