# Generated by Django 2.0.2 on 2019-11-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_proprietario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietario',
            name='data_nascimento',
            field=models.DateField(default=None, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='nome',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
