# Generated by Django 2.0.2 on 2019-11-23 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191123_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acessorios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(default=None, max_length=100)),
                ('estado', models.CharField(choices=[('otimo', 'Otimo'), ('bom', 'Bom'), ('ruim', 'Ruim')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(default=None, max_length=50)),
                ('marca', models.CharField(default=None, max_length=30)),
                ('placa', models.CharField(default=None, max_length=15)),
                ('cor', models.CharField(choices=[('preto', 'Preto'), ('azul', 'Azul'), ('amarelo', 'Amarelo'), ('branco', 'Branco'), ('prata', 'Prata'), ('vermelho', 'Vermelho')], max_length=10)),
                ('ano', models.IntegerField(default=None)),
                ('preco', models.FloatField(default=None)),
                ('imagem', models.ImageField(upload_to='imagens')),
                ('tipo', models.CharField(choices=[('moto', 'Moto'), ('carro', 'Carro')], max_length=5)),
                ('acessorios', models.ManyToManyField(to='app.Acessorios')),
            ],
        ),
        migrations.AddField(
            model_name='proprietario',
            name='profissao',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='proprietario',
            name='telefone',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Proprietario'),
        ),
    ]
