# Generated by Django 2.0.2 on 2019-11-23 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191123_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veiculo',
            old_name='imagem',
            new_name='foto_capa',
        ),
    ]
